##################################################################
# VS Code with REST Client extension is needed to use this file.
# Download at: https://aka.ms/vscode/rest-client
##################################################################

@api_host = http://localhost:7071

POST {{api_host}}/api/sessions
Accept: */*
Content-Type: application/json

{
}
