##################################################################
# VS Code with REST Client extension is needed to use this file.
# Download at: https://aka.ms/vscode/rest-client
##################################################################
# To get the bearer token, run the following command in Azure CLI:
#   az account get-access-token --query accessToken

@resourceGroup = {{$dotenv RESOURCE_GROUP}}
@subscriptionId = {{$dotenv SUBSCRIPTION_ID}}
@sessionPoolName = {{$dotenv SESSION_POOL_NAME}}
@bearerToken = {{$dotenv BEARER_TOKEN}}

### Create session pool
PUT https://management.azure.com/subscriptions/{{subscriptionId}}/resourceGroups/{{resourceGroup}}/providers/Microsoft.App/sessionPools/{{sessionPoolName}}?api-version=2024-02-02-preview
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
    "location": "northcentralusstage",
    "name": "{{sessionPoolName}}",
    "properties": {
        "poolManagementType": "Dynamic",
        "containerType": "NodeLTS",
        "scaleConfiguration": {
            "maxConcurrentSessions": 10,
            "readySessionInstances": 1
        },
        "dynamicPoolConfiguration": {
            "executionType": "Timed",
            "cooldownPeriodInSeconds": 310
        },
        "sessionNetworkConfiguration": {
            "Status": "EgressEnabled"
        }
    }
}

### Get session pool
GET https://management.azure.com/subscriptions/{{subscriptionId}}/resourceGroups/{{resourceGroup}}/providers/Microsoft.App/sessionPools/{{sessionPoolName}}?api-version=2024-02-02-preview
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

### Delete session pool
DELETE https://management.azure.com/subscriptions/{{subscriptionId}}/resourceGroups/{{resourceGroup}}/providers/Microsoft.App/sessionPools/{{sessionPoolName}}?api-version=2024-02-02-preview
Content-Type: application/json
Authorization: Bearer {{bearerToken}}
